API_URL = "https://move-excusable-hardcover.ngrok-free.dev"
RAPIDAPI_KEY = "58adc09ab6msh9830524475747dcp188661jsnd4afb05640fc"
UPSTASH_REDIS_REST_URL="https://rested-magpie-157104.upstash.io"
UPSTASH_REDIS_REST_TOKEN="gQAAAAAAAmWwAAIgcDEwNzU1MzJhZDZjMWE0YzQwYTM4MjhjMjc5NWMzYjVmYg"
PEXELS_API_KEY = "qZapgwt6GSeYPXQWFr3QoGmIXIsWvLe2n0L3P9CILn4XRMRrBuv0scxd"